Installer Updates
Woolverine94/biniou pull request #44
Opened 2024-09-05 02:04 UTC by natlamir

-when trying to install in a new vm environment, git and ffmpeg downloads would fail with cert errors. added no cert check flags. 
-whisper would throw error trying to run ffmpeg. added ffmpeg bin folder path after unzip to the env vars. 
-llama-cpp-python install would take a long time, installing from pre-built wheel for cpu.

2024-09-05 17:23 UTC, natlamir commented
For the certs, when I exported the root certs from my host machine and imported them to the guest, then it would work without needing the no cert flags in the script. I am not sure where the root certs are gotten in a fresh install. Applied all the latest windows updates, but it still didn't get those root certs that I have in the host machine.

2024-09-05 17:34 UTC, Woolverine94 commented
Thanks for the information. 

I was almost sure that the Windows updates could be a reason for this behavior, as I often not apply them when using a VM for testing biniou.

2024-09-05 20:09 UTC, Woolverine94 commented
Got it. 

It's related to the agent used to download the files. 

wget fails on some of the files with a cert error (without the no check cert flag) : python and openssl 
Suprisingly, curl have the exact opposite behavior : it only succeed to download python and openssl and fails on all other files :[

I can understand why in the case of wget (outdated binaries), not why the Windows built-in version of curl fails to download a file on github ... 

The following seems to work in all cases as a replacement for all lines starting with "wget -O" (if you want to test it) and seems to solve all the certificates issues unrelated to a **true** certificate issue :

```cmd
powershell -command "(New-Object System.Net.WebClient).DownloadFile(\"%URL_VSBT%\", \"%tmp%\vs_BuildTools.exe\")"
powershell -command "(New-Object System.Net.WebClient).DownloadFile(\"%URL_GIT%\", \"%tmp%\git.exe\")"
powershell -command "(New-Object System.Net.WebClient).DownloadFile(\"%URL_OPENSSL%\", \"%tmp%\openssl.exe\")"
powershell -command "(New-Object System.Net.WebClient).DownloadFile(\"%URL_PYTHON%\", \"%tmp%\python.exe\")"
powershell -command "(New-Object System.Net.WebClient).DownloadFile(\"%URL_FFMPEG%\", \"%tmp%\ffmpeg-master-latest-win64-gpl.zip\")"
powershell -command "(New-Object System.Net.WebClient).DownloadFile(\"%URL_VCREDIST%\", \"%tmp%\vcredist.exe\")"
```

2024-09-05 21:00 UTC, natlamir commented
That worked! It installed ffmpeg and git successfully without a cert error. And whisper is working without any ffmpeg error!

Unrelated, but do you know if I need to install a self signed cert for biniou, when I launch the browser, it always gives me this message and I have to click Advanced and continue to site:
![image](https://github.com/user-attachments/assets/56712e2e-6902-4e81-9523-fe9ddeade484)

2024-09-05 22:25 UTC, Woolverine94 commented
@natlamir, 

Yes, it's perfectly "normal". Long story short : a https connection is required to use a micro through a browser. 
Micro is usable in the whisper module, so I had to implement a self-signed certificate. Self-signed certificate are not recognized by default by your browser. 

For a lot of others reasons, you should use Firefox instead of Chromium and use [this page](https://unix.stackexchange.com/questions/644176/how-to-permanently-add-self-signed-certificate-in-firefox) to permanently add the certificate of your instance to the list of authorized ones for your browser.

I can also confirm that ffmpeg doesn't need to be added to the path in Windows installer, it is usable without that.

2024-09-06 22:00 UTC, Woolverine94 requested changes
If you can make these changes, your commit will be greatly appreciated and happily granted !

Thanks again for your contributions.

2024-09-07 14:32 UTC, Woolverine94 reviewed
Perfect ! 

Thanks a lot. 

A launch an ultimate install check on windows 11 and merge your commit right after.

2024-09-07 14:32 UTC, Woolverine94 approved these changes

2024-09-07 16:15 UTC, merged

2024-09-07 16:16 UTC, Woolverine94 commented
@natlamir,

Installation runs smooth in Windows 11.

Thanks again for your contribution.

2024-09-07 19:14 UTC, natlamir commented
Great! Good to know, I have been testing on Windows 10. Thanks!